name: build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
        - name: Checkout sources
          uses: actions/checkout@v6
      
        - name: Setup Java
          uses: actions/setup-java@v5
          with:
            distribution: 'temurin'
            java-version: 21

        - name: Make gradle executable
          run: chmod +x ./gradlew
      
        - name: Build with Gradle
          run: ./gradlew build

        - name: Upload Jar
          uses: actions/upload-artifact@v7
          with:
            path: build/libs/*.jar
            archive: false
      
