name: build

on:
  push:
    branches: [ "beta" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
        - name: Checkout sources
          uses: actions/checkout@v6

        - name: Setup Java
          uses: actions/setup-java@v5
          with:
            distribution: 'temurin'
            java-version: 21

        - name: Make gradle executable
          run: chmod +x ./gradlew

        - name: Build with Gradle
          run: ./gradlew build -Pbuild_id=${GITHUB_SHA::7}

        - name: Upload 26.1.2 jar
          uses: actions/upload-artifact@v7
          with:
            name: magicaddons-26.1.2
            path: |
              versions/26.1.2/build/libs/*.jar
              !versions/26.1.2/build/libs/*-sources.jar
            archive: false

        - name: Upload 26.2 jar
          uses: actions/upload-artifact@v7
          with:
            name: magicaddons-26.2
            path: |
              versions/26.2/build/libs/*.jar
              !versions/26.2/build/libs/*-sources.jar
            archive: false
